baseURL = "https://saikumar.dev"
languageCode = "en-us"
title = "404 [!] Found"
theme = "black-and-light"
canonifyurls = true
author = "sgummaluri"
contentdir = "content"
FootnoteReturnLinkContents = "↩"

pygmentsstyle       = "bw"
pygmentscodefences  = true

pluralizelisttitles = false

[params]
  sitename = "404 [!] Found "
  disableWebFonts = false
  dateform = "January 2006"
  datefullform = " Mon Jan 2 2006"

[[menu.main]]
    name = "GitHub"
    url  = "//github.com/sgummaluri"
[[menu.main]]
    name = "LinkedIn"
    url  = "https://www.linkedin.com/in/saikumargummaluri/"
[[menu.main]]
    name = "Resume"
    url  = "/docs/sgummaluri.pdf"
